# -*- coding: utf-8 -*-
"""
Created on Sat Nov  9 15:16:53 2019

@author: bill-
"""
##INSERT KEYS HERE AND THEY WILL BE EMPLOYED AUTOMATICALLY
#PASS ALL ARGUMENTS TO PROPERLY AUTHENTICATE
API_KEY = 'PKZH6CVO2G2P0K0ISQUP'
SECRET_KEY = 'W/ueP2wT7P1EtEktubBalxD905PCYqtV/FkW8wlS'
BASE_URL = 'https://paper-api.alpaca.markets'

