# -*- coding: utf-8 -*-
"""
Created on Sat Nov  9 15:16:53 2019

@author: bill-
"""
##INSERT KEYS HERE AND THEY WILL BE EMPLOYED AUTOMATICALLY
#PASS ALL ARGUMENTS TO PROPERLY AUTHENTICATE
API_KEY = 'PK69Q887XOA35U1DKHXA'
SECRET_KEY = 'V7PSlKq6S8amHCSKlMzRVXP1yVVa9r69t5G3grI/'
BASE_URL = 'https://paper-api.alpaca.markets'

