# -*- coding: utf-8 -*-
"""
Created on Sat Nov  9 15:16:53 2019

@author: bill-
"""
##INSERT KEYS HERE AND THEY WILL BE EMPLOYED AUTOMATICALLY
#PASS ALL ARGUMENTS TO PROPERLY AUTHENTICATE
API_KEY = 'PKS7JXWMMDQQXQNDWT2P'
SECRET_KEY = '6G14xT3kRY4VgDy58n5ULTvEKiFjYF5cD0Y8z5f2'
BASE_URL = 'https://paper-api.alpaca.markets'
