# -*- coding: utf-8 -*-
"""
Created on Sat Nov  9 15:16:53 2019

@author: bill-
"""
##INSERT KEYS HERE AND THEY WILL BE EMPLOYED AUTOMATICALLY
#PASS ALL ARGUMENTS TO PROPERLY AUTHENTICATE
API_KEY = 'PKMXERPRT87QJQIDZQ2D'
SECRET_KEY = 'l7E3t50MoQwDNtLoYO6Vpf7ZDeVI4024QV8A3icJ'
BASE_URL = 'https://paper-api.alpaca.markets'

